export const developers: RouteItem[] = [
	{
		name: 'NPM',
		path: 'https://www.npmjs.com/',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-npm',
			color: '#fff',
			bgColor: '#cb3837',
			description: '是Node的开放式模块登记和管理系统',
		},
	},
	{
		name: 'Github',
		path: 'https://github.com',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-github',
			color: '#333',
			bgColor: '#fff',
			description: '面向开源及私有软件项目的托管平台。',
		},
	},
	{
		name: 'Gitee',
		path: 'https://gitee.com/',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-gitee',
			color: '#333',
			bgColor: '#c71d23',
			description: '面向开源及私有软件项目的托管平台。',
		},
	},
	{
		name: 'iconfont',
		path: 'https://www.iconfont.cn/',
		type: ['developer', 'designer'],
		meta: {
			rank: 0,
			icon: 'app-iconfont',
			color: '#fff',
			bgColor: '#1E1E1E',
			description: '丰富的矢量图标库，提供矢量图标下载、在线存储、格式转换等功能。',
		},
	},
	{
		name: 'Echarts',
		path: 'https://echarts.apache.org/zh/index.html',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-echarts',
			bgColor: '#fff',
			description: '一款基于JavaScript的数据可视化图表库，提供直观，生动，可交互，可个性化定制的数据可视化图表。',
		},
	},
	{
		name: '知乎',
		path: 'https://www.zhihu.com',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-zhihu',
			color: '#fff',
			bgColor: '#0066ff',
			description: '搜索知乎的内容',
		},
	},
	{
		name: '稀土掘金',
		path: 'https://juejin.cn',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-juejin',
			color: '#fff',
			bgColor: '#1E80FF',
			description: '掘金是面向全球中文开发者的技术内容分享与交流平台',
		},
	},
	{
		name: 'Element-plus',
		path: 'https://element-plus.org/zh-CN/',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-element-plus',
			color: '#fff',
			bgColor: '#fff',
			description: '一个 Vue 3 UI 框架 | Element Plus',
		},
	},
	{
		name: 'MDN',
		path: 'https://developer.mozilla.org/zh-CN/',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-mdn',
			bgColor: '#15141A',
			description: '自2005年以来记录web技术，包括CSS、HTML和JavaScript。',
		},
	},
	{
		name: '图片压缩',
		path: 'https://squoosh.app/',
		type: ['developer', 'onlineTool'],
		meta: {
			rank: 0,
			icon: 'app-picture-zip',
			bgColor: '#fff',
			description: '在浏览器中压缩和比较不同编解码器的图像',
		},
	},
	{
		name: '测网速',
		path: 'https://www.speedtest.cn/',
		type: ['developer', 'onlineTool'],
		meta: {
			rank: 0,
			icon: 'app-network-speed',
			bgColor: '#fff',
			description: '提供网速测试，网络质量测试，宽带测速，Wi-Fi测速，5G测速等...',
		},
	},
	{
		name: '菜鸟教程',
		path: 'https://www.runoob.com/',
		type: 'developer',
		meta: {
			rank: 0,
			icon: 'app-cainiao',
			bgColor: '#90c751',
			size: 64,
			description: '各种编程语言的基础知识。',
		},
	},
	{
		name: '在线渐变',
		path: 'https://www.fly63.com/tool/gradient/',
		type: ['developer', 'onlineTool'],
		meta: {
			rank: 0,
			icon: 'app-jianbian',
			bgColor: '#00a0e9',
			size: 50,
			description: '在线渐变生成器。',
		},
	},
	{
		name: '字体库',
		path: 'https://www.1001fonts.com/',
		type: ['designer'],
		meta: {
			rank: 0,
			icon: 'app-font',
			bgColor: '#8e151e',
			color: '#fff',
			size: 36,
			description: '58238种免费字体，可直接下载。',
		},
	},
	{
		name: '即时设计',
		path: 'https://js.design/workspace',
		type: ['designer'],
		meta: {
			rank: 0,
			icon: 'app-jishisheji',
			bgColor: '#202020',
			color: '#fff',
			size: 60,
			description: '在线可协作的UI设计工具。',
		},
	},
	{
		name: '美叶',
		path: 'https://www.meiye.art/',
		type: ['designer'],
		meta: {
			rank: 0,
			icon: 'app-meiye',
			bgColor: '#202020',
			color: '#fff',
			description: '优质设计内容推荐平台。',
		},
	},
];
