import { categories } from './categories';
export const websites: RouteItem[] = [
	{ name: '天气', meta: { rank: 0, color: '#fff', bgColor: '#cb3837', layout: '5x2', description: '', tag: ['card'] }, component: 'Weather' },
	{ name: '日历', meta: { rank: 0, color: '#fff', bgColor: '#cb3837', layout: '5x2', description: '', tag: ['card'] }, component: 'Calendar' },
	{ name: '下班倒计时', meta: { rank: 0, color: '#fff', bgColor: '#cb3837', layout: '5x2', description: '', tag: ['card'] }, component: 'OffWork' },
	{
		name: '腾讯元宝',
		path: 'https://yuanbao.tencent.com/',
		meta: {
			rank: 1000,
			type: 'img',
			value: 'https://cdn-bot.hunyuan.tencent.com/logo.png',
			tag: ['ai'],
			size: 45,
			color: '#333',
			bgColor: '#FFFFFF',
			layout: '3x1',
			description: '腾讯混元大模型AI、DeepSeek R1 写作绘画文案翻译编程搜索阅读总结的全能助手',
		},
	},
	{
		name: 'UI生成',
		path: 'https://v0.dev/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-v0',
			tag: ['ai', 'developer'],
			size: 64,
			color: '#fff',
			bgColor: '#000',
			layout: '1x1',
			description: '使用简单的文本提示生成 UI。复制、粘贴、发送。',
		},
	},
	{
		name: '火山引擎',
		path: 'https://console.volcengine.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://res.volccdn.com/obj/volc-console-fe/images/favicon.52bcaa41.png',
			tag: ['ai'],
			size: 45,
			color: '#fff',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: '上火山引擎，用豆包大模型。',
		},
	},

	{
		name: 'NPM',
		path: 'https://www.npmjs.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-npm',
			tag: ['developer'],
			color: '#fff',
			bgColor: '#cb3837',
			layout: '1x1',
			description: '是Node的开放式模块登记和管理系统',
		},
	},
	{
		name: 'Github',
		path: 'https://github.com',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-github',
			tag: ['developer'],
			color: '#333',
			bgColor: '#fff',
			layout: '1x1',
			description: '面向开源及私有软件项目的托管平台。',
		},
	},
	{
		name: 'Gitee',
		path: 'https://gitee.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-gitee',
			tag: ['developer'],
			color: '#333',
			bgColor: '#c71d23',
			layout: '1x1',
			description: '面向开源及私有软件项目的托管平台。',
		},
	},
	{
		name: 'iconfont',
		path: 'https://www.iconfont.cn/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-iconfont',
			tag: ['developer', 'designer'],
			color: '#fff',
			bgColor: '#1E1E1E',
			layout: '1x1',
			description: '丰富的矢量图标库，提供矢量图标下载、在线存储、格式转换等功能。',
		},
	},
	{
		name: 'Animate.css',
		path: 'https://animate.style/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-animate',
			tag: ['developer'],
			bgColor: '#1E1E1E',
			color: '#fff',
			size: 70,
			layout: '1x1',
			description: 'Animate.css是一个现成的跨浏览器动画库。',
		},
	},
	{
		name: 'Echarts',
		path: 'https://echarts.apache.org/zh/index.html',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-echarts',
			tag: ['developer'],
			bgColor: '#fff',
			layout: '1x1',
			description: '一款基于JavaScript的数据可视化图表库，提供直观，生动，可交互，可个性化定制的数据可视化图表。',
		},
	},
	{
		name: '知乎',
		path: 'https://www.zhihu.com',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-zhihu',
			tag: ['news'],
			color: '#fff',
			bgColor: '#0066ff',
			layout: '1x1',
			description: '搜索知乎的内容',
		},
	},
	{
		name: '稀土掘金',
		path: 'https://juejin.cn',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-juejin',
			tag: ['developer'],
			color: '#fff',
			bgColor: '#1E80FF',
			layout: '1x1',
			description: '掘金是面向全球中文开发者的技术内容分享与交流平台',
		},
	},
	{
		name: 'Element-plus',
		path: 'https://element-plus.org/zh-CN/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-element-plus',
			tag: ['developer'],
			color: '#fff',
			bgColor: '#fff',
			layout: '1x1',
			description: '一个 Vue 3 UI 框架 | Element Plus',
		},
	},
	{
		name: 'MDN',
		path: 'https://developer.mozilla.org/zh-CN/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-mdn',
			tag: ['developer'],
			color: '#303133',
			bgColor: '#303133',
			size: 50,
			layout: '1x1',
			description: '自2005年以来记录web技术，包括CSS、HTML和JavaScript。',
		},
	},
	{
		name: '图片压缩',
		path: 'https://squoosh.app/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-picture-zip',
			tag: ['efficiency', 'designer'],
			bgColor: '#fff',
			layout: '1x1',
			description: '在浏览器中压缩和比较不同编解码器的图像',
		},
	},
	{
		name: '测网速',
		path: 'https://www.speedtest.cn/',
		meta: {
			rank: 0,
			type: 'icon',
			tag: ['efficiency'],
			value: 'app-network-speed',
			bgColor: '#fff',
			layout: '1x1',
			description: '提供网速测试，网络质量测试，宽带测速，Wi-Fi测速，5G测速等...',
		},
	},
	{
		name: '菜鸟',
		path: 'https://www.runoob.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-cainiao',
			tag: ['developer'],
			bgColor: '#90c751',
			size: 64,
			layout: '1x1',
			description: '各种编程语言的基础知识。',
		},
	},
	{
		name: '在线渐变',
		path: 'https://www.fly63.com/tool/gradient/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-jianbian',
			tag: ['designer'],
			bgColor: '#00a0e9',
			size: 50,
			layout: '1x1',
			description: '在线渐变生成器。',
		},
	},
	{
		name: '字体库',
		path: 'https://www.1001fonts.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-font',
			tag: ['designer'],
			bgColor: '#8e151e',
			color: '#fff',
			size: 36,
			layout: '1x1',
			description: '58238种免费字体，可直接下载。',
		},
	},
	{
		name: '即时设计',
		path: 'https://js.design/workspace',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-jishisheji',
			tag: ['designer'],
			bgColor: '#202020',
			color: '#fff',
			size: 62,
			layout: '1x1',
			description: '在线可协作的UI设计工具。',
		},
	},
	{
		name: '美叶',
		path: 'https://www.meiye.art/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-meiye',
			tag: ['designer'],
			bgColor: '#202020',
			color: '#fff',
			layout: '1x1',
			description: '优质设计内容推荐平台。',
		},
	},
	{
		name: 'Figma',
		path: 'https://www.figma.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-figma',
			tag: ['designer'],
			bgColor: '#202020',
			layout: '1x1',
			description: 'Figma支持多人同时在线编辑、查看和提供反馈，使得设计师、产品经理和开发人员等团队成员可以实时协作，提高设计效率。',
		},
	},
	{
		name: 'bilibili',
		path: 'https://www.bilibili.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-bilibili',
			tag: ['videos'],
			color: '#fff',
			bgColor: '#ff679a',
			size: 62,
			layout: '1x1',
			description: '视频弹幕网站，这里有及时的动漫新番，活跃的ACG氛围，有创意的Up主。',
		},
	},
	{
		name: '虎 嗅 网',
		path: 'https://www.bilibili.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-huxiu',
			tag: ['news'],
			color: '#ffff',
			bgColor: '#303133',
			size: 50,
			layout: '3x1',
			description: '科技资讯,商业评论,明星公司,动态,宏观,趋势,创业,精选,有料,干货,有用,细节,内幕。',
		},
	},
	{
		name: '豆 瓣 网',
		path: 'https://www.douban.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-douban',
			tag: ['news'],
			color: '#fff',
			bgColor: '#2f973e',
			size: 36,
			layout: '1x1',
			description: '提供图书、电影、音乐唱片的推荐、评论和价格比较，以及城市独特的文化生活。',
		},
	},
	{
		name: 'QQ音乐',
		path: 'https://y.qq.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-qq-music',
			tag: ['videos'],
			bgColor: '#fff',
			layout: '1x1',
			description: 'QQ音乐是腾讯公司推出的一款网络音乐服务产品',
		},
	},
	{
		name: '动态SVG图库',
		path: 'https://livicons.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-animation-svg',
			tag: ['designer'],
			size: 50,
			bgColor: '#20252a',
			layout: '1x1',
			description: '动画SVG图库',
		},
	},
	{
		name: 'Flaticon',
		path: 'https://www.flaticon.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-flaticon',
			tag: ['designer'],
			bgColor: '#fff',
			size: 62,
			layout: '1x1',
			description: '下载免费的图标和贴纸为您的项目',
		},
	},
	{
		name: 'Pexels',
		path: 'https://www.pexels.com/zh-cn/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-pexels',
			tag: ['designer'],
			bgColor: '#07a081',
			size: 62,
			layout: '1x1',
			description: '免费图库，图片质量不错。',
		},
	},
	{
		name: 'IconPark',
		path: ' https://iconpark.oceanengine.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-iconPark',
			tag: ['designer'],
			bgColor: '#fff',
			layout: '1x1',
			description: '高质量的iconPark,字节跳动制造。',
		},
	},
	{
		name: '好看视频',
		path: 'https://haokan.baidu.com/?sfrom=baidu-top',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-haokanshiping',
			tag: ['videos'],
			size: 60,
			color: '#FFFFFF',
			bgColor: '#fff',
			layout: '1x1',
			description: '好看视频是百度短视频旗舰品牌，拥有超百万的短视频创作者。',
		},
	},
	{
		name: '西瓜视频',
		path: 'https://www.ixigua.com/?wid_try=1',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-xigua',
			tag: ['videos'],
			bgColor: '#fff',
			layout: '1x1',
			description: '让人们看到更丰富和有深度的世界，收获轻松的获得感，点亮对生活的好奇',
		},
	},
	{
		name: '抖音',
		path: 'https://www.douyin.com/?recommend=1',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-douyin',
			tag: ['videos'],
			bgColor: '#111',
			size: 50,
			layout: '1x1',
			description: '抖音让每一个人看见并连接更大的世界。',
		},
	},
	{
		name: '新浪微博',
		path: 'https://weibo.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-weibo',
			tag: ['news'],
			bgColor: '#fff',
			size: 62,
			layout: '1x1',
			description: '新浪微博',
		},
	},
	{
		name: '今日头条',
		path: 'https://www.toutiao.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-toutiao',
			tag: ['news'],
			bgColor: '#fff',
			size: 62,
			layout: '1x1',
			description: '今日头条，头条，头条网，头条新闻，今日头条官网。',
		},
	},
	{
		name: '36氪',
		path: 'https://36kr.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-36ke',
			tag: ['news'],
			bgColor: '#4182F1',
			size: 62,
			layout: '1x1',
			description: '独家的视角为用户深度剖析最前沿的资讯',
		},
	},
	{
		name: 'ChatGPT',
		path: 'https://chat.openai.com/',
		meta: {
			rank: 100,
			type: 'icon',
			value: 'app-openAi',
			tag: ['ai'],
			bgColor: '#000',
			color: '#fff',
			layout: '3x1',
			description: '独家的视角为用户深度剖析最前沿的资讯',
		},
	},
	{
		name: '百度翻译',
		path: 'https://fanyi.baidu.com/mtpe-individual/multimodal?aldtype=16047#/auto/zh',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-baidufanyi',
			tag: ['efficiency'],
			bgColor: '#0299FF',
			color: '#fff',
			layout: '1x1',
			description: '百度翻译',
		},
	},
	{
		name: '语雀',
		path: 'https://www.yuque.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-yuque',
			tag: ['efficiency'],
			bgColor: '#fff',
			layout: '1x1',
			description: '博客技术栈在线工具资源网站UI库后端技术稀土掘金微信百...',
		},
	},
	{
		name: 'Discord',
		path: 'https://discord.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-discord',
			bgColor: '#5865f2',
			tag: ['ai'],
			color: '#fff',
			layout: '1x1',
			description: '用户可以创建和加入各种类型的服务器',
		},
	},
	{
		name: '高德地图',
		path: 'https://ditu.amap.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-gaode',
			tag: ['efficiency'],
			bgColor: '#fff',
			size: 66,
			layout: '1x1',
			description: '高德地图',
		},
	},
	{
		name: 'loading',
		path: 'https://css-loaders.com/shapes/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-loading',
			tag: ['designer'],
			bgColor: '#fff',
			color: '#333',
			layout: '1x1',
			description: '加载状态',
		},
	},
	{
		name: '人人都是产品经理',
		path: 'http://www.woshipm.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-product',
			tag: ['designer'],
			bgColor: '#fff',
			layout: '1x1',
			description: '人人都是产品经理致力为产品新人',
		},
	},
	{
		name: '墨刀',
		path: 'https://modao.cc/brand/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-modao',
			tag: ['designer'],
			bgColor: '#fff',
			layout: '1x1',
			description: 'AI时代的专业级原型设计工具',
		},
	},
	{
		name: '腾讯视频',
		path: 'https://v.qq.com/',
		meta: { rank: 0, type: 'icon', value: 'app-tenxun', tag: ['videos'], bgColor: '#fff', layout: '1x1', description: '腾讯视频' },
	},
	{
		name: '蓝湖',
		path: 'https://lanhuapp.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-lanhu',
			tag: ['designer'],
			bgColor: '#fff',
			layout: '1x1',
			description: '助互联网团队更好地管理文档和设计图',
		},
	},
	{
		name: 'YouTube',
		path: 'https://www.youtube.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-youguan',
			tag: ['videos'],
			bgColor: '#fff',
			layout: '1x1',
			description: '好看的外国自媒体网站，访问需要点手段。',
		},
	},
	{
		name: 'Chrome',
		path: 'https://www.google.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-chrome',
			tag: ['news'],
			size: 50,
			bgColor: '#fff',
			layout: '1x1',
			description: '最棒的浏览器，访问需要点手段。',
		},
	},
	{
		name: 'Bing',
		path: 'https://www.bing.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-bing',
			tag: ['news'],
			size: 50,
			bgColor: '#fff',
			layout: '1x1',
			description: '微软的也不错，适合程序员。',
		},
	},
	{
		name: '百度',
		path: 'https://www.baidu.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-baidu',
			tag: ['news'],
			size: 50,
			bgColor: '#fff',
			layout: '1x1',
			description: '适合搜娱乐八卦之类的。',
		},
	},
	{
		name: 'jsRun',
		path: 'http://cs.jsrun.net/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-jsRun',
			tag: ['developer'],
			size: 61,
			bgColor: '#fff',
			layout: '1x1',
			description: 'js在线运行，C#在线编译。',
		},
	},
	{
		name: 'codesandbox',
		path: 'https://codesandbox.io/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-codesandbox',
			tag: ['developer'],
			size: 50,
			color: '#000000',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: '很强的在线编辑器。',
		},
	},
	{
		name: 'DeepSeek',
		path: 'https://chat.deepseek.com/',
		meta: {
			rank: 180,
			type: 'img',
			value: 'https://chat.deepseek.com/favicon.svg',
			tag: ['ai'],
			size: 45,
			color: '#333',
			bgColor: '#FFFFFF',
			layout: '3x1',
			description: '深度求索, AGI, 人工智能底层模型, 开源模型',
		},
	},
	{
		name: 'AiPPT',
		path: 'https://www.aippt.cn',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://www.aippt.cn/favicon.ico',
			tag: ['ai'],
			size: 60,
			color: '#fff',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: '提供一键生成高质量PPT的解决方案',
		},
	},
	{
		name: 'unDraw',
		path: 'https://undraw.co/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-unDraw',
			tag: ['developer', 'designer'],
			size: 61,
			color: '#fff',
			bgColor: '#5952D1',
			layout: '1x1',
			description: 'svg插图,免费下载',
		},
	},
	{
		name: '搜狐新闻',
		path: 'https://news.sohu.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-souhunews',
			tag: ['news'],
			size: 62,
			bgColor: '#F2C81C',
			color: '#333',
			layout: '1x1',
			description: '搜狐新闻，偶尔会给你个大爆料。',
		},
	},
	{
		name: '500PX',
		path: 'https://500px.com.cn/community/index.html',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-500px',
			tag: ['art'],
			size: 40,
			color: '#333',
			bgColor: '#fff',
			layout: '1x1',
			description: '视觉500px摄影师社区',
		},
	},
	{
		name: '35PHOTO',
		path: 'https://35photo.pro/',
		meta: {
			rank: 0,
			type: 'text',
			value: '摄',
			tag: ['art'],
			size: 20,
			color: '#fff',
			bgColor: '#FF4500',
			layout: '1x1',
			description: '专业作者照片目录',
		},
	},
	{
		name: '有道云笔记',
		path: 'https://note.youdao.com/web/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-youdaoyun',
			tag: ['efficiency'],
			size: 62,
			color: '#fff',
			bgColor: '#FF4500',
			layout: '1x1',
			description: '记录，成为更好的自己',
		},
	},
	{
		name: '小霸王',
		path: 'https://www.yikm.net/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-xiaobawang',
			tag: ['games'],
			size: 61,
			layout: '1x1',
			description: '小霸王，其乐无穷 。红白机，FC在线游戏，街机游戏，街机在线',
		},
	},
	{
		name: 'AI生成PPT',
		path: 'https://gamma.app/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://gamma.app/favicons/favicon-192.svg',
			tag: ['ai'],
			size: 45,
			color: '#fff',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: '提出想法的新媒介。\n由人工智能提供支持。',
		},
	},
	{
		name: 'Nest.js',
		path: 'https://docs.nestjs.cn/10/introduction',
		meta: {
			rank: 0,
			type: 'img',
			value: new URL('/assets/img/app-nest.png', import.meta.url).href,
			tag: ['developer'],
			size: 45,
			color: '#FFFFFF',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: '可扩展的 Node.js 服务器端应用程序的框架。',
		},
	},
	{
		name: 'Node.js',
		path: 'https://nodejs.org/en',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://nodejs.org/static/images/favicons/favicon.png',
			tag: ['developer'],
			size: 45,
			color: '#fff',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: 'Node.js® 是一个免费、开源、跨平台的 JavaScript 运行环境，可让开发人员创建服务器、Web 应用程序、命令行工具和脚本。',
		},
	},
	{
		name: 'Vant',
		path: 'https://vant-ui.github.io/vant/#/zh-CN',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://fastly.jsdelivr.net/npm/@vant/assets/logo.png',
			tag: ['developer'],
			size: 45,
			color: '#fff',
			bgColor: '#FFFFFF',
			layout: '1x1',
			description: '轻量、可定制的移动端 Vue 组件库',
		},
	},
	{
		name: '3D资源',
		path: 'https://polyhaven.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://polyhaven.com/favicon.ico',
			tag: ['designer', 'vr'],
			size: 46,
			color: '#fff',
			bgColor: '#fff',
			layout: '1x1',
			description: '公共3D资源库',
		},
	},
	{
		name: 'Pixi.js',
		path: 'https://pixijs.huashengweilai.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://pixijs.huashengweilai.com/favicon.png',
			tag: ['developer'],
			size: 45,
			color: '#fff',
			bgColor: '#fff',
			layout: '1x1',
			description: 'PixiJS的强项是速度。在2D渲染方面，PixiJS是最快的。',
		},
	},
	{
		name: 'GSAP',
		path: 'https://gsap.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: new URL('/assets/img/app-gsap.webp', import.meta.url).href,
			tag: ['developer'],
			size: 45,
			color: '#fff',
			bgColor: '#fff',
			layout: '1x1',
			description: '动画库',
		},
	},
	{
		name: 'WebPickerTools',
		path: 'https://www.codeandweb.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://www.codeandweb.com/favicons/icon-144x144-cf4325912be17b4b1dd1914fefcba95f.png',
			tag: ['developer'],
			size: 45,
			color: '#fff',
			bgColor: '#fff',
			layout: '1x1',
			description: '适用于您的 2D 游戏项目的精灵表打包器工具',
		},
	},
	{
		name: 'Kimi',
		path: 'https://kimi.moonshot.cn/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://statics.moonshot.cn/kimi-chat/favicon.ico',
			tag: ['ai'],
			size: 45,
			color: '#fff',
			bgColor: '#000',
			layout: '3x1',
			description:
				'Kimi是一款学生和职场人的新质生产力工具。帮你解读论文，写代码查BUG，策划方案，创作小说，多语言翻译。有问题问Kimi，一键解决你的所有难题',
		},
	},
	{
		name: 'AI生成图片',
		path: 'https://app.leonardo.ai/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://app.leonardo.ai/favicon.ico',
			tag: ['ai', 'designer'],
			size: 45,
			color: '#fff',
			bgColor: '#000000',
			layout: '3x1',
			description: '以前所未有的质量、速度和风格一致性为您的项目创建生产质量的视觉资产。',
		},
	},
	{
		name: 'Tripo',
		path: 'https://www.tripo3d.ai/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://www.tripo3d.ai/favicon.ico',
			tag: ['designer', 'ai'],
			size: 57,
			color: '#fff',
			bgColor: '#0f0f0f',
			layout: '3x1',
			description: 'Tripo AI 是面向设计师、开发人员和创意人员的终极 3D AI 工具，提供效率、精确度和创新性。',
		},
	},
	{
		name: '探索点子',
		path: 'https://www.pinterest.com/',
		meta: {
			rank: 0,
			type: 'icon',
			value: 'app-pinterest',
			tag: ['designer'],
			size: 45,
			color: '#333',
			bgColor: '#fff',
			layout: '3x1',
			description: '发现想要尝试的食谱、家居创意、时尚灵感及其他创意点子。',
		},
	},
	{
		name: 'Dribbble',
		path: 'https://dribbble.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://cdn.dribbble.com/assets/favicon-99944ff731bb44d3a947810ca8728f177f8deac035a3a4342120c385fd7acb9d.svg',
			tag: ['designer'],
			size: 45,
			color: '#333',
			bgColor: '#fff',
			layout: '3x1',
			description: '探索世界顶级设计师',
		},
	},
	{
		name: 'design',
		path: 'https://www.designspiration.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://www.designspiration.com/favicon.ico',
			tag: ['designer'],
			size: 45,
			color: '#333',
			bgColor: '#fff',
			layout: '3x1',
			description: '保存并探索 激发您创造力 的想法。',
		},
	},
	{
		name: 'WES',
		path: 'https://www.awwwards.com/',
		meta: {
			rank: 0,
			type: 'img',
			value: 'https://assets.awwwards.com/assets/images/favicon-safari.svg',
			tag: ['designer'],
			size: 50,
			color: '#333',
			bgColor: '#fff',
			layout: '3x1',
			description: '世界上最优秀的开发人员、设计师',
		},
	},
];
